import "../styles/globals.scss";
import type { AppProps } from "next/app";
import Head from "next/head";
import Layout from "../components/Layout/Layout";
import { Roboto } from "@next/font/google";
import store, { persister } from "../store/store";
import { PersistGate } from "redux-persist/integration/react";
import { Provider } from "react-redux";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export default function App({ Component, pageProps }: AppProps) {
    return (
        <>
            <Provider store={store}>
                <PersistGate loading={null} persistor={persister}>
                    <Head>
                        <title>iPhones-NextJS</title>
                        <meta
                            name="iPhones-NextJS"
                            content="Generated by SikorskyDev"
                        />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    <Layout>
                        <style jsx global>
                            {`
                                html {
                                    font-family: ${roboto.style.fontFamily};
                                }
                            `}
                        </style>
                        <Component {...pageProps} />
                    </Layout>
                </PersistGate>
            </Provider>
        </>
    );
}
